spring:
  application:
    name: speaker-platform-

  datasource:
    url: jdbc:mysql://localhost:3306/lecture_management?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: localpw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        data-loader: 2

  data:
    redis:
      host: localhost
      port: 6379

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.dahye.speakerplatform
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true              # ?? ?? ??
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true               # Swagger UI ???? : ?? ?? => <http://localhost:8080/swagger-ui/index.html>
    path: /api-swagger.html         # Swagger UI ?? ?? ?? =>
    tags-sorter: alpha          # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    operations-sorter: alpha    # alpha: ??? ? ?? ??, method: HTTP Method ? ??

app:
  jwtSecret: OUQgqBBpggKnxB9tgzUKH5rijqRLliXWpcxjkBfF4bLSR//XtBKhFejo2w6JFlQRZEGfWRnX1EcXHv6w0Oyy/Q==