spring:
  application:
    name: speaker-platform-

  datasource:
    url: jdbc:mysql://localhost:3306/lecture_management?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: localpw
    driver-class-name: com.mysql.cj.jdbc.Driver